//! Ability bar renderer - renders ability bar to an offscreen FBO for compositing.
//! Uses a separate Slint window with PBO-based rendering to avoid CPU readback.
//! Implements throttled updates to reduce Slint dirty checking overhead.

use std::rc::Rc;

use slint::platform::software_renderer::{MinimalSoftwareWindow, PremultipliedRgbaColor};
use slint::PhysicalSize;

use crate::gl_call;
use crate::ui::game::views::ability_bar::SlotDisplayData;

// The AbilityBarStandalone component is generated by slint::include_modules!() in game_root.rs
// We need to import it from there. The generated types are in the same module as GameRoot.
// We'll use a type alias to avoid having to specify the full path everywhere.
type AbilityBarStandalone = crate::ui::game::views::game_root::AbilityBarStandalone;

/// Size of the ability bar in logical pixels (from game_root.slint).
const ABILITY_BAR_WIDTH: u32 = 380;
const ABILITY_BAR_HEIGHT: u32 = 68;

/// Update interval in seconds - only update Slint properties this often.
/// 33ms = ~30 updates/sec, which is plenty for cooldown animations.
const UPDATE_INTERVAL: f64 = 0.033;

/// Renders the ability bar to an offscreen FBO using Slint software rendering.
/// The texture can be sampled directly for compositing without CPU readback.
pub struct AbilityBarRenderer {
    window: Rc<MinimalSoftwareWindow>,
    ability_bar: AbilityBarStandalone,
    buffer: Vec<PremultipliedRgbaColor>,
    texture: u32,
    pbo: u32,
    width: u32,
    height: u32,

    // throttling and change detection
    cached_slots: [SlotDisplayData; 6],
    cached_show: bool,
    last_update_time: f64,
    needs_render: bool,
}

impl AbilityBarRenderer {
    /// Create a new ability bar renderer.
    pub fn new(scale_factor: f32) -> Self {
        // create the Slint component
        let ability_bar = AbilityBarStandalone::new().unwrap();

        let window = crate::ui::slint_platform::get_last_created_window()
            .expect("Expected window to be created for AbilityBarStandalone");

        // set scale factor first, then size
        window.dispatch_event(slint::platform::WindowEvent::ScaleFactorChanged { scale_factor });

        // calculate physical size from logical size
        let width = (ABILITY_BAR_WIDTH as f32 * scale_factor) as u32;
        let height = (ABILITY_BAR_HEIGHT as f32 * scale_factor) as u32;

        window.set_size(PhysicalSize::new(width, height));

        let pixel_count = (width * height) as usize;
        let buffer = vec![PremultipliedRgbaColor::default(); pixel_count];

        // create GL texture
        let texture = Self::create_gl_texture(width, height);

        // create PBO for async upload
        let mut pbo = 0;
        unsafe {
            gl_call!(gl::GenBuffers(1, &mut pbo));
        }

        Self {
            window,
            ability_bar,
            buffer,
            texture,
            pbo,
            width,
            height,
            cached_slots: Default::default(),
            cached_show: false,
            last_update_time: -999.0, // force first update
            needs_render: true,
        }
    }

    /// Create a GL texture for the ability bar.
    fn create_gl_texture(width: u32, height: u32) -> u32 {
        unsafe {
            let mut tex = 0u32;
            gl_call!(gl::GenTextures(1, &mut tex));
            gl_call!(gl::BindTexture(gl::TEXTURE_2D, tex));
            gl_call!(gl::TexParameteri(
                gl::TEXTURE_2D,
                gl::TEXTURE_MIN_FILTER,
                gl::LINEAR as i32
            ));
            gl_call!(gl::TexParameteri(
                gl::TEXTURE_2D,
                gl::TEXTURE_MAG_FILTER,
                gl::LINEAR as i32
            ));
            gl_call!(gl::TexParameteri(
                gl::TEXTURE_2D,
                gl::TEXTURE_WRAP_S,
                gl::CLAMP_TO_EDGE as i32
            ));
            gl_call!(gl::TexParameteri(
                gl::TEXTURE_2D,
                gl::TEXTURE_WRAP_T,
                gl::CLAMP_TO_EDGE as i32
            ));
            gl_call!(gl::TexImage2D(
                gl::TEXTURE_2D,
                0,
                gl::RGBA as i32,
                width as i32,
                height as i32,
                0,
                gl::RGBA,
                gl::UNSIGNED_BYTE,
                std::ptr::null()
            ));
            gl_call!(gl::BindTexture(gl::TEXTURE_2D, 0));
            tex
        }
    }

    /// Update ability bar data. Uses throttling and change detection to minimize Slint updates.
    pub fn update(&mut self, show: bool, slots: [SlotDisplayData; 6], elapsed_time: f64) {
        // check if we should update based on throttle interval
        let time_since_update = elapsed_time - self.last_update_time;
        let should_update_time = time_since_update >= UPDATE_INTERVAL;

        // always update immediately if show state changes or any ability becomes ready
        let show_changed = show != self.cached_show;
        let ready_state_changed = slots
            .iter()
            .zip(self.cached_slots.iter())
            .any(|(new, old)| new.is_ready != old.is_ready);

        let should_update = should_update_time || show_changed || ready_state_changed;

        if !should_update {
            return;
        }

        // update cached state
        self.cached_slots = slots.clone();
        self.cached_show = show;
        self.last_update_time = elapsed_time;
        self.needs_render = true;

        // update Slint properties
        self.ability_bar.set_show(show);
        self.ability_bar.set_slot_m1(slots[0].to_slint());
        self.ability_bar.set_slot_m2(slots[1].to_slint());
        self.ability_bar.set_slot_q(slots[2].to_slint());
        self.ability_bar.set_slot_e(slots[3].to_slint());
        self.ability_bar.set_slot_shift(slots[4].to_slint());
        self.ability_bar.set_slot_r(slots[5].to_slint());
    }

    /// Render the ability bar to the FBO texture using PBO for zero-copy upload.
    pub fn render(&mut self) {
        if !self.needs_render {
            return;
        }

        self.window.request_redraw();

        self.window.draw_if_needed(|renderer| unsafe {
            gl_call!(gl::BindBuffer(gl::PIXEL_UNPACK_BUFFER, self.pbo));

            // allocate PBO if needed
            let size = (self.width * self.height * 4) as isize;
            gl_call!(gl::BufferData(
                gl::PIXEL_UNPACK_BUFFER,
                size,
                std::ptr::null(),
                gl::STREAM_DRAW
            ));

            // map PBO and render directly to it
            let ptr = gl::MapBuffer(gl::PIXEL_UNPACK_BUFFER, gl::WRITE_ONLY);
            if !ptr.is_null() {
                let pixel_count = (self.width * self.height) as usize;
                let buffer_slice =
                    std::slice::from_raw_parts_mut(ptr as *mut PremultipliedRgbaColor, pixel_count);
                renderer.render(buffer_slice, self.width as usize);
                gl_call!(gl::UnmapBuffer(gl::PIXEL_UNPACK_BUFFER));
            }
        });

        // upload to texture from PBO
        unsafe {
            gl_call!(gl::BindTexture(gl::TEXTURE_2D, self.texture));
            gl_call!(gl::TexSubImage2D(
                gl::TEXTURE_2D,
                0,
                0,
                0,
                self.width as i32,
                self.height as i32,
                gl::RGBA,
                gl::UNSIGNED_BYTE,
                std::ptr::null() // reads from bound PBO
            ));
            gl_call!(gl::BindBuffer(gl::PIXEL_UNPACK_BUFFER, 0));
            gl_call!(gl::BindTexture(gl::TEXTURE_2D, 0));
        }

        self.needs_render = false;
    }

    /// Get the GL texture ID for compositing.
    pub fn get_texture_id(&self) -> u32 {
        self.texture
    }
}

impl Drop for AbilityBarRenderer {
    fn drop(&mut self) {
        unsafe {
            gl_call!(gl::DeleteTextures(1, &self.texture));
            gl_call!(gl::DeleteBuffers(1, &self.pbo));
        }
    }
}
