//! Ability bar renderer - renders ability bar to an offscreen FBO for compositing.
//! Uses a separate Slint window with renderer-owned texture upload helpers.
//! Implements throttled updates to reduce Slint dirty checking overhead.

use std::rc::Rc;

use slint::platform::software_renderer::{MinimalSoftwareWindow, PremultipliedRgbaColor};
use slint::PhysicalSize;

use crate::gl_call;
use crate::renderer::{Renderer, UiTextureDescriptor, UiUploadBuffer};
use crate::ui::game::views::ability_bar::SlotDisplayData;
use crate::ui::image_cache::UiImageCache;

// The AbilityBarStandalone component is generated by slint::include_modules!() in game_root.rs
// We need to import it from there. The generated types are in the same module as GameRoot.
// We'll use a type alias to avoid having to specify the full path everywhere.
type AbilityBarStandalone = crate::ui::game::views::game_root::AbilityBarStandalone;

/// Size of the ability bar in logical pixels (from game_root.slint).
const ABILITY_BAR_WIDTH: u32 = 380;
const ABILITY_BAR_HEIGHT: u32 = 68;

/// Update interval in seconds - only update Slint properties this often.
/// 100ms = 10 updates/sec, which is plenty for cooldown animations.
const UPDATE_INTERVAL: f64 = 0.1;

/// Renders the ability bar to an offscreen FBO using Slint software rendering.
/// The texture can be sampled directly for compositing without CPU readback.
pub struct AbilityBarRenderer {
    window: Rc<MinimalSoftwareWindow>,
    ability_bar: AbilityBarStandalone,
    texture: u32,
    ui_upload_buffer: UiUploadBuffer,
    width: u32,
    height: u32,

    // throttling and change detection
    cached_slots: [SlotDisplayData; 3],
    cached_show: bool,
    last_update_time: f64,
    needs_render: bool,
}

impl AbilityBarRenderer {
    /// Create a new ability bar renderer.
    pub fn new(scale_factor: f32) -> Self {
        // create the Slint component
        let ability_bar = AbilityBarStandalone::new().unwrap();

        let window = crate::ui::slint_platform::get_last_created_window()
            .expect("Expected window to be created for AbilityBarStandalone");

        // set scale factor first, then size
        window.dispatch_event(slint::platform::WindowEvent::ScaleFactorChanged { scale_factor });

        // calculate physical size from logical size
        let width = (ABILITY_BAR_WIDTH as f32 * scale_factor) as u32;
        let height = (ABILITY_BAR_HEIGHT as f32 * scale_factor) as u32;

        window.set_size(PhysicalSize::new(width, height));

        // create GL texture
        let texture = Renderer::create_ui_texture(
            UiTextureDescriptor::rgba_linear_clamped(width, height),
            None,
        );

        // Native builds currently back this with a PBO; the API stays upload-path neutral.
        let ui_upload_buffer = Renderer::create_ui_upload_buffer();

        Self {
            window,
            ability_bar,
            texture,
            ui_upload_buffer,
            width,
            height,
            cached_slots: Default::default(),
            cached_show: false,
            last_update_time: -999.0, // force first update
            needs_render: true,
        }
    }

    /// Update ability bar data. Uses throttling and change detection to minimize Slint updates.
    pub fn update(
        &mut self,
        show: bool,
        slots: [SlotDisplayData; 3],
        image_cache: &mut UiImageCache,
        elapsed_time: f64,
    ) {
        // check if we should update based on throttle interval
        let time_since_update = elapsed_time - self.last_update_time;
        let should_update_time = time_since_update >= UPDATE_INTERVAL;

        // check for structural changes (not cooldown progress) that should trigger immediate update
        let show_changed = show != self.cached_show;

        // compare slots while ignoring cooldown progress
        let mut slots_changed = false;
        for i in 0..3 {
            let s1 = &slots[i];
            let s2 = &self.cached_slots[i];
            if s1.visible != s2.visible
                || s1.icon_path != s2.icon_path
                || s1.is_ready != s2.is_ready
                || s1.ability_id != s2.ability_id
                || s1.ability_name != s2.ability_name
            {
                slots_changed = true;
                break;
            }
        }

        let should_update = should_update_time || show_changed || slots_changed;

        if !should_update {
            return;
        }

        // update cached state
        self.cached_slots = slots.clone();
        self.cached_show = show;
        self.last_update_time = elapsed_time;
        self.needs_render = true;

        // update Slint properties
        self.ability_bar.set_show(show);
        self.ability_bar.set_slot_q(slots[0].to_slint(image_cache));
        self.ability_bar.set_slot_e(slots[1].to_slint(image_cache));
        self.ability_bar.set_slot_r(slots[2].to_slint(image_cache));
    }

    /// Render the ability bar to the texture using the renderer-owned upload path.
    pub fn render(&mut self) {
        if !self.needs_render {
            return;
        }

        self.window.request_redraw();

        self.window.draw_if_needed(|renderer| {
            let size = (self.width * self.height * 4) as isize;
            let pixel_count = (self.width * self.height) as usize;
            Renderer::write_ui_upload_buffer(
                self.ui_upload_buffer,
                size,
                pixel_count,
                true,
                |buffer_slice: &mut [PremultipliedRgbaColor]| {
                    renderer.render(buffer_slice, self.width as usize);
                },
            );
        });

        Renderer::update_ui_texture_from_upload_buffer(
            self.texture,
            self.ui_upload_buffer,
            UiTextureDescriptor::rgba_linear_clamped(self.width, self.height),
        );

        self.needs_render = false;
    }

    /// Get the GL texture ID for compositing.
    pub fn get_texture_id(&self) -> u32 {
        self.texture
    }
}

impl Drop for AbilityBarRenderer {
    fn drop(&mut self) {
        unsafe {
            gl_call!(gl::DeleteTextures(1, &self.texture));
            Renderer::delete_ui_upload_buffer(self.ui_upload_buffer);
        }
    }
}
