[[entities]]
entity_type = "TrashGuy"
faction = "Player"
position = [0.0, 10.0, 0.0]
rotation = [0.0, -0.9239, 0.0, 0.3827]
weapons = ["DoubleAxe", "OrcSword"]
base_speed = 7.0
jump_height = 1.5
health = 100_000.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [5.0, 10.0, 5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

# =============================================================================
# LOTTA GUYS
# =============================================================================

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

[[entities]]
entity_type = "TrashGuy"
faction = "Enemy"
position = [-5.0, 10.0, -5.0]
rotation = [0.0, 0.8701, 0.0, 0.4929]
weapons = ["OrcSword", "DoubleAxe"]
base_speed = 5.5
health = 100.0

# =============================================================================
# END LOTTA GUYS
# =============================================================================

# [[entities]]
# entity_type = "YRobot"
# faction = "Enemy"
# position = [-49.0062, -5.3441, -119.7894]
# rotation = [0.0, 0.8701, 0.0, 0.4929]
# weapons = ["OrcSword", "DoubleAxe"]

# 
# [[entities]]
# entity_type = "YRobot"
# faction = "Enemy"
# position = [-20.0062, -4.5597, -119.7894]
# rotation = [0.0, -1.0, 0.0, 0.0]
# 
[[entities]]
entity_type = "MooseMan"
faction = "Enemy"
position = [-10.3714, 10.0, -10.8407]
rotation = [0.0, 0.0, 0.0, 1.0]
health = 100_000.0

[[entities]]
entity_type = "Cactus1"
faction = "Static"
position = [-100.3714, -5.72, -117.8407]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "Cactus2"
faction = "Static"
position = [-90.3714, -5.72, -127.8407]
rotation = [0.0, 0.0, 0.0, 1.0]

[[entities]]
entity_type = "Rock1"
faction = "Static"
position = [-110.3714, -5.4, -100.8407]
rotation = [0.0, 0.0, 0.0, 1.0]


[[entities]]
entity_type = "BareBush1"
faction = "Static"
position = [2.0, 5.0, 1.5]
rotation = [0.0, 0.0, 0.0, 1.0]
# 
# [[entities]]
# entity_type = "TreeFoliage"
# faction = "Static"
# position = [-3.9293, 19.2934, 14.0707]
# rotation = [0.0, 0.0, 0.0, 1.0]
# 
# [[entities]]
# entity_type = "TreeTrunk"
# faction = "Static"
# position = [-4.0707, 19.238, 13.9293]
# rotation = [0.0, 0.0, 0.0, 1.0]
# 
# [[entities]]
# entity_type = "TreeFoliage"
# faction = "Static"
# position = [19.1117, 28.5057, 16.6127]
# rotation = [0.0, 0.0, 0.0, 1.0]
# 
# [[entities]]
# entity_type = "TreeTrunk"
# faction = "Static"
# position = [18.9703, 28.4139, 16.4713]
# rotation = [0.0, 0.0, 0.0, 1.0]
# 
# # [[entities]]
# # entity_type = "TrashGuy"
# # faction = "Static"
# # position = [-86.8102, -4.8841, -78.8799]
# # rotation = [0.0, -0.9239, 0.0, 0.3827]
